menu:
  Home:
  Archives: archives
  #Categories: categories
  About: about
  #Rss: atom.xml

widgets:
- search
- category
- tag
- tagcloud
- links

links_title: 友情链接
links:
    xxx : https://sdfadf.com

date_format: YYYY-MM-DD
search:
  bing

excerpt_link: 阅读全文 


twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: disqus
# Facebook comment
#facebook:
#  appid: 123456789012345
#  comment_count: 5
#  comment_width: 840
#  comment_colorscheme: light

language: zh-CN
